### ISSUE TITLE
Not able to produce the usage message

### ISSUE THREAD

**Issue by tushardave26** [araraloren/perl6-getopt-advance#1]
Hello, Loren

Thanks for making the module.

I am a newbie to the Perl 6 world and still getting my head around it. I started playing with Perl 6 recently. I am writing a command line program. So, I searched Perl 6 module directory for command line parsing modules and found your module. The module looks nice. However, I am having a difficult time understanding the syntax for it. I wrote a simple program as shown below. When I run the program on the command line without mandatory command line arguments, it did not produce the usage message. Can you please help me to understand my mistake/s? Thanks for your help.

```
#!~/.rakudobrew/bin/perl6
use v6.c;
use Data::Dump;
use Getopt::Advance;
use Getopt::Advance::Helper;
use Getopt::Advance::Exception;

my OptionSet $optset .= new();

$optset.push("c|count=i", "set some counter");

&getopt($optset, :autohv, helper => &ga-helper2);

say "Hello Perl 6 !!! \c[BELL]";

exit;
```

I am using ```Getopt::Advance:ver('0.0.6')``` and ```Rakudo version 2017.07```

Best,
Tushar

**Comment by araraloren** [comment]
Yeah, the module has a little bug. And sorry about the document is not too much.
I fix the bug of :autohv and ga-helper2 in current version 0.0.8, and will make more document later.
The help message will be produced when command line parse failed or the :autohv is True.
Please use zef  update to the last version, and test your script again. 
And Perl6 has a build-in command line tools `MAIN`, you can try it first.
Thanks

**Comment by tushardave26** [comment]
I tried to update the module using ```zef install Getopt::Advance```. After that I tried to find whether it actually update the module or not via ```zef --installed list | fgrep -w "Getopt::Advance"```.  Below is the output of the command:

```
===> Found via /Applications/Rakudo/share/perl6
===> Found via /Applications/Rakudo/share/perl6/site
Getopt::Advance:ver('0.0.6'):auth('github:araraloren')
```
Does the GitHub repo host the updated codebase? If so, I can try to install it directly.

Thanks for your help.

**Comment by tushardave26** [comment]
I tried to install a aspecific version of the module via ```zef install "Getopt::Advance:ver('0.0.8')"``` but did not get any success. Below is the output of the command:

```
===> Searching for: Getopt::Advance:ver('0.0.8')
No candidates found matching identity: Getopt::Advance:ver('0.0.8')
```
Any thoughts?

**Comment by tushardave26** [comment]
Alright!! Finally, I am able to install the updated version of the module. It seems like you updated the module but ```zef``` repository is not updated for it and find the olde version all the time. Therefore, I installed the module directly from the ```GitHub``` using ```$ zef -v install https://github.com/araraloren/perl6-getopt-advance/archive/master.zip```.

Then, I tried to run my script and following is the output. The script spits out the usage message as expected but did not exit immediately after the failure. It still prints the last statement that I have in my script. This is possibly a bug. Can you please share your thoughts on this?

```
$ perl6 commandLineHandling.p6 
Usage:
commandLineHandling.p6  [-c|--count=<integer>]  

-c|--count=<integer> set some counter

Hello Perl 6 !!! 🔔
```

**Comment by araraloren** [comment]
@tushardave26 
You can try `zef update` first.

Sorry guys, I confused the usage of `:autohv`. I have AFK a long time.
It should works like this:
When you have a `help` or `version` option, it will automate print the help message or version message when it set by user. 
Without `:autohv`, you should deal the `help` option manually.
I will change the code back.

**Comment by araraloren** [comment]
@tushardave26 
And what do you want the script do ?

**Comment by tushardave26** [comment]
@araraloren 

The script merely print the message, if all the required command line options are provided. If any of the options is not provided, the script should terminate and display the usage message. But in my case, the script displays the usage message and also print the line (i.e. Hello Perl 6 !!!). I hope this makes sense.

**Comment by araraloren** [comment]
`If any of the options is not provided, the script should terminate and display the usage message.`
No, the script will not terminated. No option provide can means everything is  default behavior of one script.
In my module, the sub `&getopt` will not terminated the script(by call exit) except module user want print a help or no OptionSet matched.

**Comment by araraloren** [comment]
If you need that behavior, you should write something like:
```
#!/usr/bin/env perl6

use v6.c;
use Data::Dump;
use Getopt::Advance;
use Getopt::Advance::Helper;
use Getopt::Advance::Exception;

my OptionSet $optset .= new();

$optset.push("c|count=i", "set some counter");
$optset.insert-main(sub main() {
	if True #`[something you want test] {
		&ga-want-helper();
	}
});

&getopt($optset, :autohv, helper => &ga-helper2);

say "Hello Perl 6 !!! \c[BELL]";
exit;
```
You can test the option or something like @*ARGS(The module not touch this variable, it remain contains all command line arguments), and do what you want .

**Comment by araraloren** [comment]
@tushardave26 So, if you don't have any question now. I close this issue.

**Comment by tushardave26** [comment]
@araraloren .. sorry!! yes, please.
