### ISSUE TITLE
ga-pre-parser returns wrong option set in ReturnValue

### ISSUE THREAD

**Issue by vrurg** [araraloren/perl6-getopt-advance#13]
When pre-parsing CLI options noa array is the only way to determine the command used in the command line. See the following code:

     my OptionSet @os;
     my OptionSet $os;

     for <help cmd1 cmd2> -> $cmd {
         $os .= new;
         $os.insert-cmd( $cmd );
         @os.push: $os;
     }

     say "> pre-parser";
     my $rv = getopt( @(<cmd1>), |@os, :parser( &ga-pre-parser ) );

     $os = $rv.optionset;

     say "get-cmd: ", $os.get-cmd{0}.name;
     say "success: ", $os.get-cmd{0}.success;
     say "NOA: ", $rv.noa[0];

     say "> main parser";
     $rv = getopt( @(<cmd2>), |@os );

     $os = $rv.optionset;

     say "get-cmd: ", $os.get-cmd{0}.name;
     say "success: ", $os.get-cmd{0}.success;

It uses both parsers to demonstrate expected behavior as to my view the main parser does the right job. Here is the output of the code:

> ```
> > pre-parser
> get-cmd: help
> success: False
> NOA: cmd1
> > main parser
> get-cmd: cmd2
> success: True
> ```

It turns out that the problem is quite old and presented in both v0.3 and v1.0 branches.

**Comment by araraloren** [comment]
And you should reset the cmd before next using :)

**Comment by vrurg** [comment]
I did not know about the reset, missed it in the documentation. Thanks! But in my actual code it's not relevant because two different lists of `OptionSet` are used.

**Comment by araraloren** [comment]
Okay, it's fine if different `OptionSet` are used.
I will try to update the documents these days, the old one outdated.
