### ISSUE TITLE
ga-helper is broken in v1.0 with regard to multiple option sets

### ISSUE THREAD

**Issue by vrurg** [araraloren/perl6-getopt-advance#14]
I have a second issue today.

     my OptionSet @os;
     my OptionSet $os;

     for <help cmd1 cmd2> -> $cmd {
         $os .= new;
         $os.insert-cmd( $cmd );
         @os.push: $os;
     }

     ga-helper( @os, $*OUT );

With v0.3.8 the code outputs:

> ```
> Usage:
> ./getopt.p6 help
> 
> ./getopt.p6 cmd1
> 
> ./getopt.p6 cmd2
> ```

With v1.0.3-1.0.6:

> ```
> Usage:
> ./getopt.p6 cmd2
> ```

BTW, I would like to ask for some improvements to the help output, if possible. First, it would be great to remove blank linkes between commands and options; or have an option for that. With a long list of options it would spare some screen space.

Another great thing to have would be to have annotations for commands and make it possible to generate helper output in a form:

```
util cmd1      This command is useful
util cmd2      This command is to confuse the user
util help      Will print help for any other command. Try 'help cmd1' 
```

**Comment by araraloren** [comment]
I fixed it.
Also I add a compact-help option to the `&ga-helper`(using it by pass it to `&getopt`), default is True.

**Comment by araraloren** [comment]
For the `cmd`, I plan add the annotation argument to it.
So we can generate the annotations for the commands.
Actually you can just make your own helper if you want more customization information by steal the code of `&ga-helper`.
Most of thing already generated by the `&ga-helper-impl`.

**Comment by araraloren** [comment]
@vrurg But I plan to make the format like this
```
Usage:
  ./sample/test.p6 help [-h] 
  ./sample/test.p6 cmd1 [-h] 
  ./sample/test.p6 cmd2 [-h] 
CMDs:
  help using help feature
  cmd1 using cmd1 feature
  cmd2 using cmd2 feature
OPTIONs:
  -h print help message
  -h print help message
  -h print help message
```
Put the annotations in first line will be too long for most common cases.

**Comment by vrurg** [comment]
I was thinking about own helper already. In a bit different way, though. The point is that I'm currently using all three help formats:

- command list for when no command is specified
- commands with options when it's just `help` command
- specific command with expanded options with `help cmd` 

It is sufficient for my task for now.

Regarding your plans – I like them. But if you don't mind I would suggest skipping the ./sample/test.p6 part from _Usage:_. It only takes valuable screen space and distracts from actual commands and their options. Perhaps something like:

```
Usage:
    ./sample/test.p6 <command>  [<options>]
Commands:
    help using help feature
    ...
Options:
    ...
```

Would be sufficient here. Though _Options_ are better be printed only individually for a command's help (i.e. when helper is called on a single `OptionSet`) because they'd flood the screen making it hard for a user to find what he's looking for. Perhaps what could be done to tidy up the output is printing just a list of options without annotations below the command from their `OptionSet`:

```
...
Commands:
    using help feature:
        help <command> [-l|--long] [--ansi-colors]
    using cmd1:
        cmd [-h] [--cmd-specific]
```

But I would only do the following:

- print a list of commands with annotations if no command is found in the command line or command is not recognized
- print complete list of options for a specific command if command was recognized but there is a error in its options

Anything else would be up to the developer. Anyway, the best practice of helping the user is providing him with an explanatory page from the program manual, as `git help <command>` does. ;)

**Comment by vrurg** [comment]
BTW, I didn't say the most important thing: thank you for your prompt replies and fixes! I do appreciate them!

**Comment by araraloren** [comment]
Yeah, good idea.
I consider the comand (such as `git`) design, better not print the `OPTIONs` for multiple options.

**Comment by araraloren** [comment]
@vrurg I improve the Helper module, how do you think this version?

**Comment by araraloren** [comment]
BTW there is a Debug option in the `Getopt::Advance::Utils`.
Set like this `Getopt::Advance::Utils::Debug::setLevel(0)` will print the debug message.

**Comment by vrurg** [comment]
Almost everything looks good now! Grouping of options with their respective commands is great! I would only remove duplication of the command. It would be the best either have a command in its own line and options on the next line aligned by some spaces. Or have them all on the same line and align options up to the longest command name:

```
thisislongcommand  [--opt1] [--opt2]
shortcmd           [--file=<string>] [--check]
cmd                [--count=<int>]
```
This would make it easier for a user to find a command he needs.

And now come two issues. One is minor but annoying. The introduced debug output produces a lot of lines like these:

```
Use of uninitialized value of type Any in string context.
Methods .^name, .perl, .gist, or .say can be used to stringify it to something meaningful.
  in block  at /Users/vrurg/.rakudobrew/moar-2018.09/install/share/perl6/site/sources/E7666270F0CA8F07544C2173A0550FFD9B92E519 (Getopt::Advance::Parser) line 597
Use of uninitialized value of type Any in string context.
Methods .^name, .perl, .gist, or .say can be used to stringify it to something meaningful.
  in block  at /Users/vrurg/.rakudobrew/moar-2018.09/install/share/perl6/site/sources/E7666270F0CA8F07544C2173A0550FFD9B92E519 (Getopt::Advance::Parser) line 447
Use of uninitialized value of type Any in string context.
Methods .^name, .perl, .gist, or .say can be used to stringify it to something meaningful.
  in block  at /Users/vrurg/.rakudobrew/moar-2018.09/install/share/perl6/site/sources/E7666270F0CA8F07544C2173A0550FFD9B92E519 (Getopt::Advance::Parser) line 449
Use of uninitialized value of type Any in string context.
Methods .^name, .perl, .gist, or .say can be used to stringify it to something meaningful.
  in method Str at /Users/vrurg/.rakudobrew/moar-2018.09/install/share/perl6/site/sources/6F33E4219E950435D465C74EEC4E40B219F56874 (Getopt::Advance::Argument) line 13
Use of uninitialized value of type Any in string context.
Methods .^name, .perl, .gist, or .say can be used to stringify it to something meaningful.
  in method Str at /Users/vrurg/.rakudobrew/moar-2018.09/install/share/perl6/site/sources/6F33E4219E950435D465C74EEC4E40B219F56874 (Getopt::Advance::Argument) line 13
Use of uninitialized value of type Any in string context.
Methods .^name, .perl, .gist, or .say can be used to stringify it to something meaningful.
  in block  at /Users/vrurg/.rakudobrew/moar-2018.09/install/share/perl6/site/sources/E7666270F0CA8F07544C2173A0550FFD9B92E519 (Getopt::Advance::Parser) line 597
Use of uninitialized value of type Any in string context.
Methods .^name, .perl, .gist, or .say can be used to stringify it to something meaningful.
  in block  at /Users/vrurg/.rakudobrew/moar-2018.09/install/share/perl6/site/sources/E7666270F0CA8F07544C2173A0550FFD9B92E519 (Getopt::Advance::Parser) line 447
Use of uninitialized value of type Any in string context.
Methods .^name, .perl, .gist, or .say can be used to stringify it to something meaningful.
  in block  at /Users/vrurg/.rakudobrew/moar-2018.09/install/share/perl6/site/sources/E7666270F0CA8F07544C2173A0550FFD9B92E519 (Getopt::Advance::Parser) line 449
Use of uninitialized value of type Any in string context.
```

And then there is a bug: help is not printed for a command without annotation. If neither command in a list of `OptionSet` has an annotation then the code dies:

```
Cannot convert -Inf to Int:
  in method __gen_max_widths at /Users/vrurg/.rakudobrew/moar-2018.09/install/share/perl6/site/sources/E1AB0CB82FFB3259DA19FED7E147502F41FED18F (Terminal::Table::Generator) line 243
  in method generate at /Users/vrurg/.rakudobrew/moar-2018.09/install/share/perl6/site/sources/E1AB0CB82FFB3259DA19FED7E147502F41FED18F (Terminal::Table::Generator) line 434
  in sub array-to-table at /Users/vrurg/.rakudobrew/moar-2018.09/install/share/perl6/site/sources/C24F21A7F08CC97A7C9E0F62C32556C1ABA2171C (Terminal::Table) line 24
  in block  at /Users/vrurg/.rakudobrew/moar-2018.09/install/share/perl6/site/sources/C4ADF0D06BE182BDBE5758808665ACCEE72011C6 (Getopt::Advance::Helper) line 303
  in sub ga-helper at /Users/vrurg/.rakudobrew/moar-2018.09/install/share/perl6/site/sources/C4ADF0D06BE182BDBE5758808665ACCEE72011C6 (Getopt::Advance::Helper) line 264
  in sub showhelp at /Users/vrurg/.rakudobrew/moar-2018.09/install/share/perl6/site/sources/6D0A1412E32D76D4335B7BB229C83C790132E97D (Getopt::Advance) line 89
  in block  at /Users/vrurg/.rakudobrew/moar-2018.09/install/share/perl6/site/sources/6D0A1412E32D76D4335B7BB229C83C790132E97D (Getopt::Advance) line 129
  in any  at /Users/vrurg/.rakudobrew/moar-2018.09/install/share/perl6/site/precomp/B69B93ACC13369F3646F85010429409F6CCA3481/6D/6D0A1412E32D76D4335B7BB229C83C790132E97D line 1
  in sub ga-non-option-error at /Users/vrurg/.rakudobrew/moar-2018.09/install/share/perl6/site/sources/BDF0BCEF5BFF1B4FEF6399556ACD6EAECF2B28C6 (Getopt::Advance::Exception) line 36
  in method check-cmd at /Users/vrurg/.rakudobrew/moar-2018.09/install/share/perl6/site/sources/6D0A1412E32D76D4335B7BB229C83C790132E97D (Getopt::Advance) line 668
  in sub  at /Users/vrurg/.rakudobrew/moar-2018.09/install/share/perl6/site/sources/E7666270F0CA8F07544C2173A0550FFD9B92E519 (Getopt::Advance::Parser) line 393
  in method CALL-ME at /Users/vrurg/.rakudobrew/moar-2018.09/install/share/perl6/site/sources/E7666270F0CA8F07544C2173A0550FFD9B92E519 (Getopt::Advance::Parser) line 535
  in sub ga-parser at /Users/vrurg/.rakudobrew/moar-2018.09/install/share/perl6/site/sources/E7666270F0CA8F07544C2173A0550FFD9B92E519 (Getopt::Advance::Parser) line 600
  in sub getopt at /Users/vrurg/.rakudobrew/moar-2018.09/install/share/perl6/site/sources/6D0A1412E32D76D4335B7BB229C83C790132E97D (Getopt::Advance) line 110
  in sub try-opts at ./getopt.p6 line 87
  in block <unit> at ./getopt.p6 line 106
```

I checked for what is going on in the `Getopt::Advance::Helper` prior to line 303 where it passes the control over to the table generator. `.cmdusage` returns empty array if command has no annotation. Consequently, `@allcmd` ends up being empty which causes the table generator to fail.

Hope this helps.

**Comment by araraloren** [comment]
Can not reproduce the debug issue, I don't know what mess the debug output.
Would you mind provide the code you test ?
I thought not print the cmd not have annotation at start, but seems like we should print them though not have a annotation.
And I generate a output of new style(using it by add a `one-section-cmd` named argument to `&getopt`):
```
Usage:
  ./sample/test.p6 <COMMANDs> [POSITIONs] [OPTIONs] 

COMMANDs
  remove Using remove command

  add    Using add command   

  abc                        

OPTIONs
  remove    [foo@1] [module@*] [-out=<string>] [-ver=<string>] [-d|--debug] [-v|--version] [-h|--help] [-md] 

  add       [foo@1] [module@*] [-out=<string>] [-ver=<string>] [-d|--debug] [-v|--version] [-h|--help] [-md] 

  abc       [-v|--version] [-h|--help] [-d|--debug]                                                          

  NOCOMMAND [-d|--debug] [-v|--version] [-h|--help] 
```
What about this ? I would consider the user may insert two or more cmd to one `OptionSet`.
So I prefer old style. It's hard to unify them in one style.

**Comment by vrurg** [comment]
This code should demonstrate the debug code issue:

```
     my %src2 =
         help => {
             opts => [
                 "compact=b" => "compact help",
             ],
             pos => {
                 topic => [
                     1,
                     sub ( $os, $help-topic ) {
                         note "Need help for topic $help-topic";
                     }
                 ],
             },
         },
         cmd1 => {
             opts => [
                 "op1=s" => "option 1",
                 "op2=b" => "option 2",
             ],
         },
         cmd2 => {
         },
         cmd3 => {
         },
     ;

     sub try-opts ( %src, @args ) {
         my OptionSet @os;
         my OptionSet $os;

         for %src.keys -> $cmd {
             $os .= new;
             my @c = $cmd;
             @c.push: $_ with %src{$cmd}<annotation>;
             $os.insert-cmd( |@c );

             $os.append: |$_ with %src{$cmd}<opts>;
             with %src{$cmd}<pos> {
                 for .keys -> $pos-name {
                     $os.insert-pos(
                         $pos-name,
                         |$_{$pos-name}
                     );
                 }
             }

             @os.push: $os;
         }

         note " >> getopt({@args})";
         my $rv = getopt( @args, |@os, :compact-help );
     }

     note "--- No command, no annotations";
     try-opts( %src2, @() );
```

I was experimenting with annotations, so it has more code than needed. But I'm tight on time currently to write a new sample.

The output looks fantasic! I have certain doubts about user readability of `@N` `@*` in positionals. `...` instead of `@*` would be more familiar to most people. But that's absolutely minor and doesn't worth bothering. 

What would be really helpful for a user is sorting options by name in individual command help. For example, due to the way I collect options from different sources I get the following output:

```
COMMANDs
  initdb
OPTIONs
  --conlevel=<string>    console output level
  --database=<string>    database name
  --dbpassword=<string>  database password
  --dbport=<integer>     SQL server port
  --dbserver=<array>     SQL server
  --dbservers=<array>    list of SQL servers
  --dbtable=<string>     database table
  --dbuser=<string>      database user
  --logfile=<string>     log file
  --loglevel=<string>    log level
  --redis-server=<array> Redis server(s) in form host:port
  --test                 test mode
  -c|--config=<string>   config file
  -f|--force             force initialize, don't prompt for confirmation
  -t|--test-table        initialize test table
```
It is just a handful of options for now, not a big deal to scan them all. But with longer lists some ordering would be very helpful. But then again, it's nothing critical. I'm gonna display a help page anyway at some point.

Regarding the unification and multiple commands – agree. I don't need multi-command for now, so missed this point. Gave it a try with my test code and looks pretty good. A style note: `<COMMAND>` would me more correct than currently used `<COMMANDs>`.

Otherwise I just have upgraded to 1.1.1 and I see it doing the right thing for. Thank you for this work!

**Comment by araraloren** [comment]
I found you pass something like `@()` is actually `(Nil, )` (print by `dd @()`), I am not sure what' this .
So currently the debug output is fine.
And I fixed the command hit `<COMMANDs>` to `<COMMAND>`.
Currently everything of help is fine in 1.1.2.

**Comment by vrurg** [comment]
You're totally right, it was supposed to be `@( )` – with a space between braces which is an empty `List`. `[]` could be used as well in this place. It was a test for no options on the command line. With correct syntax there are no warnings produced. I think this could be ignored then.

Thanks for pointing out to this because I have same error in another location in my work code! 🤦🏻‍♂️

I'm gonna re-check everything later today. But so far everything looks great!

Thank you!

**Comment by araraloren** [comment]
Okay, let me know if something is borken by the new version.
There may still have potential bug in 1.* 😄
