### ISSUE TITLE
feature request: merge two OptionSet

### ISSUE THREAD

**Issue by vrurg** [araraloren/perl6-getopt-advance#7]
I would like to use this module to provide command interface for my utility; i.e., something like:

```
# util cmd1 --option1
# util cmd2 --option2
```

The handling of options will be in the hands of my internal framework. Commands and their options will be defined by other classes, implementing this utility. But there gonna be a couple of options common for all commands. In `git` style these are options going _before_ the command (i.e. `git -p <command>`. This module doesn't provide this functionality, unfortunately. So, I would like to implement different approach where the common options could be collected in their own OptionsSet which could later be merged with other sets responsible for defining their commands. But there is no legal way to merge two set objects into a third one.

Would it be possible to implement this feature? I could manually transfer content of `main`, `multi`, and `radio` attributes but not sure if this is really a good idea.

**Comment by araraloren** [comment]
Hi, there is another parser (`ga-pre-parser`) you can using to parse the common option.
It's not throw any exception when process unknow options.
This is mean you can process some options before your command going on.
You can refer this file : [fs](https://github.com/araraloren/perl6-app-findsource/blob/master/bin/fs#L17)
Notice the `-l` option is loaded before we add other options.

And about merge the `OptionSet`,
how about clone the `OptionSet` first, and add other options and nonoptions ?

**Comment by araraloren** [comment]
@vrurg 
I just mean this, don't override the things from common OptionSet, just add it after
```
my $commonos = OptionSet.new;
.... # the code about the common option
 
my $oneos = $commonos.clone(); # not pass any paramters
... # add your cmd/pos/options

my $twoos = $commonos.clone(); # another parameters
...# add your cmd/pos/options
```

**Comment by araraloren** [comment]
@vrurg 
People will first consider the MAIN feature of Perl 6, not other getopt module.
So there is not much people using my this module.
I just write it for myself, so it is complicate, not well designed.

**Comment by vrurg** [comment]
Unfortunately, your `.clone` approach won't work for me too because some components can define common options too. The procedure is the following: traverse a dynamically defined set of modules, collect options in a `".common" => OptionSet, :command1(OptionSet), :command2(OptionSet),...` hash. `.common` options are injected into the command-specific `OptionSet`s. Actually, what it does now is cloning of a command's `OptionSet` and then prepending `@.main`, `@.multi`, and `@.radio` attributes with corresponding content from `.common`. Rough, but it works.

After that `ReturnValue` is preserved and is accessible by any subcomponent for configuration. Because it's a framework it needs some level of flexibility in order to satisfy different needs of utilities using it.

For this reason I can't use `MAIN` too because it is only good for predefined sets of options.

Overall, I'm pretty satisfied with your module even with the workaround I currently use. The merging option would simply make things cleaner. If I manage to convince you to implement it then it would greatly fit into `.clone` concept; say, `$os-merged = $os1.clone( :merge($os2) )`. I would even defined `+` operator: `$os-merged = $os1 + $os2`, but this one is mostly for the fun of it. ;)

PS. Not sure how `Supply` fits into option parsing. I'm intrigued! :)

**Comment by araraloren** [comment]
@vrurg 
yeah, It's easy to implement it.
I will add an merge method to OptionSet, but will not disturb the clone method, this will confused the user.
I am try to using `Supply` here, maybe you can refer the branch `supply`.

**Comment by vrurg** [comment]
I could use the branch. Though how much different is it in its API?

**Comment by araraloren** [comment]
@vrurg 
Not much clear currently, but I will provide old API.
It was in exploratory stage, it'll be nice if you can give me some idea.
The new way to using module maybe like this:
```
my $os = OptionSet.new;

... # code hanle the options/nonoptions (short for `o/no`).
... # add `o/no` through the API [ push append insert* ]
... # or read the sub signature, and convert it to `o/no`, like Python.Fire does
... # or using the old string for getopt(C)
... # or read them from other things, such as JSON, YAML

react  {
    whenever $os.opt("a") #`[ or $os<a> ] {
        ... # do what you want
    }
    whenever $os.get-main("mainname") {
        ... # do what you want
    }
    whenever &getopt($os, :long, :short, :xopt) {

    }
}
```

**Comment by vrurg** [comment]
I need to think about it. Take into account too that I'm not yet really familiar with asynchronous semantics of Perl6 (it's only a two months since I seriously started with it).

However, for the moment it looks like an overkill to me. Is there any advantage in asynchronous option processing? Besides, quite often one option may depend on another. Or sometimes they could even be mutually dependent. In such case sequential processing isn't even possible!

It is also not clear to me if `start` creating a new thread is a good thing or not.

So, I'm rather confused and, as it was said, need to consider it carefully. It's very likely that I'm missing something.

What I do like a lot is using JSON/YAML for definitions. I'm egoistic here, but it would significantly ease my life making the code collecting options from many sources at run time obsolete. They could be defined once per application build!

**Comment by araraloren** [comment]
@vrurg The all things is in one thread. 
Actually my tools module load the options from JSON file: [configs](https://github.com/araraloren/perl6-app-findsource/tree/master/config).

**Comment by vrurg** [comment]
The lack of time plays tricks on me: I don't think every thought until the end. Would I be able to use JSON/YAML then use of a specially crafted structure would solve my matter too! So, they could be good helpers, not a complete solution.

As to the threads, here is an excerpt from Pertl6 `start` documentation:

> For each value in the original supply, the code object is scheduled on another thread

My tests didn't display this behavior either and everything was executed in the same thread. But this could change in the future versions of rakudo.

**Comment by araraloren** [comment]
@vrurg  I am not using the `start`. I am using the `react` keyword. Can not find the documents said something about thread-safe. But it is safe for our modules. I will do more test and make sure it is no trouble here.

**Comment by vrurg** [comment]
And I was wrong again, sorry! Dunno why have I decided that there is `start` somewhere in the code.
